### ISSUE TITLE
Day21 comment

### ISSUE THREAD

**Issue by sliard** [SimonBaars/AdventOfCode-Java#2]
Hi !
Sorry to create an issue for that but I read a lot all your solutions and I have a question :)
You write a comment:  !(A && B && C) || D
But it's code  !(A && B && C) && D no ?

https://github.com/SimonBaars/adventOfCode-2019/blob/f3c80d6d57cff5f8d26c685d578b2cd2eedfbf38/src/main/java/com/sbaars/adventofcode2019/days/Day21.java#L17

Thx

**Comment by SimonBaars** [comment]
Very well noticed! I'll fix the comment! :-)
